### ISSUE TITLE
Repeated code

### ISSUE THREAD

**Issue by ryanfox1985** [Dudisek/name_project#1]
Hi Peter,

I found repeated code:
https://github.com/Dudisek/name_project/blob/master/name.rb#L16
And
https://github.com/Dudisek/name_project/blob/master/name.rb#L21

Maybe you can apply some idea from:
http://programmers.stackexchange.com/questions/107458/how-to-remove-duplicate-code-in-general

Regards.

**Comment by petdud** [comment]
Thanks Guillermo! I created a private method to make it dry 👍

**Comment by ryanfox1985** [comment]
Good!

Here you have  documentation about smart commits:
https://help.github.com/articles/closing-issues-via-commit-messages

You can link commits with issues and close issues.

Regards.

**Comment by petdud** [comment]
Great tip! It works like a magic! Thanks 👍
